 
stages:                                                                                                                                         
 - build                                                                                                                                        
 - deploy                                                                                                                                       
                                                                                                                                                
maven-build:                                                                                                                                    
  image: maven:3-jdk-11                                                                                                                         
  stage: build                                                                                                                                  
  script: "mvn package -B"                                                                                                                      
  artifacts:                                                                                                                                    
    paths:                                                                                                                                      
      - target/stock-tracking-be-0.0.1-SNAPSHOT.jar
                                                                                                              
deploy:
    stage: deploy
    image: alpine:3.11
    before_script:
        - apk update && apk add openssh-client bash
        - mkdir -p ~/.ssh
        - eval $(ssh-agent -s)
        - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
        - touch ~/.ssh/config
        - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
        - ssh-keyscan -H $EC2_IPADDRESS >> ~/.ssh/known_hosts
    script:
        - echo "Deploying started..."
        - ssh ubuntu@$EC2_IPADDRESS "sudo systemctl stop stockapp.service"
        - scp ./target/stock-tracking-be-0.0.1-SNAPSHOT.jar ubuntu@$EC2_IPADDRESS:~/stock-app/
        - ssh ubuntu@$EC2_IPADDRESS "sudo systemctl start stockapp.service"
        - echo "Finished deploying the app."
    only:
        - dev
    